// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Alert(arg1, arg2, arg3) {
  return window['go']['backend']['App']['Alert'](arg1, arg2, arg3);
}

export function CloseMe() {
  return window['go']['backend']['App']['CloseMe']();
}

export function GetConfig() {
  return window['go']['backend']['App']['GetConfig']();
}

export function GetLibraryPath() {
  return window['go']['backend']['App']['GetLibraryPath']();
}

export function Greet(arg1) {
  return window['go']['backend']['App']['Greet'](arg1);
}

export function Notify(arg1, arg2, arg3) {
  return window['go']['backend']['App']['Notify'](arg1, arg2, arg3);
}

export function SetLibraryPath(arg1) {
  return window['go']['backend']['App']['SetLibraryPath'](arg1);
}
