// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Alert(arg1:string,arg2:string,arg3:string):Promise<void>;

export function CloseMe():Promise<void>;

export function Greet(arg1:string):Promise<string>;

export function Notify(arg1:string,arg2:string,arg3:string):Promise<void>;
